#cmakedefine01 KPAC_NO_SOLID

#define CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}"
#define LIBEXEC_INSTALL_DIR "${LIBEXEC_INSTALL_DIR}"

#cmakedefine01 HAVE_ARPA_NAMESER_COMPAT_H
#cmakedefine01 HAVE_ARPA_NAMESER8_COMPAT_H
#cmakedefine01 HAVE_NETINET_IN_H
#cmakedefine01 HAVE_SYS_TYPES_H
#cmakedefine01 HAVE_SYS_PARAM_H
#cmakedefine01 HAVE___RES_INIT_IN_RESOLV_LIBRARY
#cmakedefine01 HAVE_RES_INIT_IN_RESOLV_LIBRARY
#cmakedefine01 HAVE_RESOLV_LIBRARY
#cmakedefine01 HAVE_STDINT_H
